source "https://rubygems.org"

gem "bootstrap-sass", "~> 3.4"
gem "bourbon", "~> 4.3"
gem "font-awesome-sass", "~> 4.7"
gem "jquery-middleman", "~> 3.1"
gem "localeapp", "~> 3.1"
gem "middleman", "~> 4.3"
gem "middleman-autoprefixer", "~> 2.10"
gem "middleman-blog", "~> 4.0"
gem "middleman-favicon-maker", "~> 4.1"
gem "middleman-livereload", "~> 3.4"
gem "middleman-minify-html", "~> 3.4"
gem "middleman-rouge", "~> 0.0"
gem "nokogiri", "~> 1.10"
gem "redcarpet", "~> 3.5"
gem "rouge", "~> 3.17"
