source "https://rubygems.org"

gem "bootstrap-sass"
gem "bourbon"
gem "font-awesome-sass"
gem "haml", "~> 4.0"
gem "jquery-middleman"
gem "localeapp"
gem "middleman", "~> 3.3"
gem "middleman-autoprefixer", "~> 2.10"
gem "middleman-blog"
gem "middleman-favicon-maker", "~> 3.7"
gem "middleman-livereload", "~> 3.4"
gem "middleman-minify-html"
gem "middleman-syntax", "~> 3.2"
gem "nokogiri"
gem "redcarpet", "~> 3.5"
